---

- name: Setting up logging configuration
  hosts: poc_ios

  tasks:
    - name: Setting logging host
      ios_logging:
        dest: host
        name: "{{ log_server }}"
        state: present

    - name: Setting logging buffer size
      ios_logging:
        dest: buffered
        size: "{{ log_buffer_size }}"

    - name: Save configuration when modified
      ios_config:
        save_when: changed
