---

- name: Test getting facts
  hosts: poc_ios
  gather_facts: no

  tasks:
    - name: Get facts info from device
      ios_facts:
        gather_subset:
          - hardware
      register: hardware_info

    - name: Create MD file
      template: src=version_and_model.j2 dest=files/version_and_model.md
      run_once: true
